# Analise usando Querys

In [14]:
import pandas as pd
import datetime

In [15]:
data = pd.read_csv('Dados/fifa_clear.csv')
data.head()

,Unnamed: 0,Unnamed: 0.1,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,...,GKReflexes,Release Clause,Defending,General,Mental,Passing,Mobility,Power,Rating,Shooting
0,0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,...,8.0,€226.5M,29,89,71,87,91,74,94,88
1,1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,...,11.0,€127.1M,27,88,73,81,91,83,94,88
2,2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,...,11.0,€228.1M,28,85,72,80,94,69,92,84
3,3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,...,94.0,€138.6M,16,26,43,39,66,54,92,21
4,4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,...,13.0,€196.4M,59,79,81,92,81,76,92,85

# Qual o melhor jogador por posição?

In [16]:
data.iloc[data.groupby(data['Position'])['Overall'].idxmax()][['Position', 'Name', 'Age', 'Club',
                             'Nationality','Overall']].sort_values(by = 'Overall',
                                        ascending = False).style.background_gradient(cmap = 'pink')

# Quais os jogadores mais novos do jogo?

In [17]:
youngest = data[data['Age'] == 16][['Name', 'Age', 'Club', 'Nationality', 'Overall']]
youngest.sort_values(by = 'Overall', ascending = False).head().style.background_gradient(cmap = 'magma')

# Quais os jogadores mais velhos?

In [18]:
data.sort_values('Age', ascending = False)[['Name', 'Age', 'Club',
                              'Nationality', 'Overall']].head(15).style.background_gradient(cmap = 'Wistia')

# Jogador com mais tempo de Clube

In [19]:
now = datetime.datetime.now()
data['Join_year'] = data.Joined.dropna().map(lambda x: x.split(',')[1].split(' ')[1])
data['Years_of_member'] = (data.Join_year.dropna().map(lambda x: now.year - int(x))).astype('int')
membership = data[['Name', 'Club', 'Years_of_member']].sort_values(by = 'Years_of_member', ascending = False).head(10)
membership.set_index('Name', inplace=True)
membership.style.background_gradient(cmap = 'Reds')

# Quais as skills mais importantes por posição

In [20]:
player_features = ('Acceleration', 'Aggression', 'Agility', 
                   'Balance', 'BallControl', 'Composure', 
                   'Crossing', 'Dribbling', 'FKAccuracy', 
                   'Finishing', 'GKDiving', 'GKHandling', 
                   'GKKicking', 'GKPositioning', 'GKReflexes', 
                   'HeadingAccuracy', 'Interceptions', 'Jumping', 
                   'LongPassing', 'LongShots', 'Marking', 'Penalties')

for i, val in data.groupby(data['Position'])[player_features].mean().iterrows():
    print('Position {}: {}, {}, {}'.format(i, *tuple(val.nlargest(4).index)))

Position CAM: Balance, Agility, Acceleration
Position CB: Jumping, Aggression, HeadingAccuracy
Position CDM: Aggression, Jumping, Balance
Position CF: Agility, Balance, Acceleration
Position CM: Balance, Agility, Acceleration
Position GK: GKReflexes, GKDiving, GKPositioning
Position LAM: Agility, Balance, Acceleration
Position LB: Acceleration, Balance, Agility
Position LCB: Jumping, Aggression, HeadingAccuracy
Position LCM: Balance, Agility, BallControl
Position LDM: Aggression, BallControl, LongPassing
Position LF: Balance, Agility, Acceleration
Position LM: Acceleration, Agility, Balance
Position LS: Acceleration, Agility, Finishing
Position LW: Acceleration, Agility, Balance
Position LWB: Acceleration, Agility, Balance
Position RAM: Agility, Balance, Acceleration
Position RB: Acceleration, Balance, Jumping
Position RCB: Jumping, Aggression, HeadingAccuracy
Position RCM: Agility, Balance, BallControl
Position RDM: Aggression, Jumping, BallControl
Position RF: Agility, Acceleration, Balance
Position RM: Acceleration, Agility, Balance
Position RS: Acceleration, Agility, Jumping
Position RW: Acceleration, Agility, Balance
Position RWB: Acceleration, Agility, Balance
Position ST: Acceleration, Jumping, Finishing

<ipython-input-20-8a8ae214e2d4>:9: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  for i, val in data.groupby(data['Position'])[player_features].mean().iterrows():

# Os 10 melhores jogadores canhotos

In [21]:
data[data['Preferred Foot'] == 'Left'][['Name', 'Age', 'Club',
         'Nationality', 'Overall']].sort_values(by = 'Overall',
            ascending = False).head(10).style.background_gradient(cmap = 'bone')

# Os 10 melhores jogadores destros

In [22]:
data[data['Preferred Foot'] == 'Right'][['Name', 'Age', 'Club',
                    'Nationality', 'Overall']].sort_values(by = 'Overall',
                            ascending = False).head(10).style.background_gradient(cmap = 'copper')

# Os jogadores mais caros com o contrato proximo de acabar

In [23]:
x = data[data['Contract Valid Until'] == "2020"]

def extract_value_from(column):
    out = column.replace('€', '')
    if 'M' in out:
        out = float(out.replace('M', ''))*1000000
    elif 'K' in column:
        out = float(out.replace('K', ''))*1000
    return float(out)

x['Wage'] = x['Wage'].apply(extract_value_from)

x[['Name','Nationality','Club','Age', 'Wage']].sort_values(by = 'Wage', ascending = False).head(10)

<ipython-input-23-db1ea6b97616>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Wage'] = x['Wage'].apply(extract_value_from)

            Name Nationality                 Club  Age      Wage
6      L. Modrić     Croatia          Real Madrid   32  420000.0
8   Sergio Ramos       Spain          Real Madrid   32  380000.0
5      E. Hazard     Belgium              Chelsea   27  340000.0
13   David Silva       Spain      Manchester City   32  285000.0
3         De Gea       Spain    Manchester United   27  260000.0
49    Jordi Alba       Spain         FC Barcelona   29  250000.0
24  G. Chiellini       Italy             Juventus   33  215000.0
31    C. Eriksen     Denmark    Tottenham Hotspur   26  205000.0
21     E. Cavani     Uruguay  Paris Saint-Germain   31  200000.0
46      K. Navas  Costa Rica          Real Madrid   31  195000.0

# Função para retornar o jogador

In [26]:
def report(player):
    return data[data['Name'] == player][['Nationality','Club',
                                         'Overall','Potential',
                                         'Contract Valid Until','Wage',
                                        'International Reputation']].reset_index(drop = True).T

report('L. Messi')

                                     0
Nationality                  Argentina
Club                      FC Barcelona
Overall                             94
Potential                           94
Contract Valid Until              2021
Wage                             €565K
International Reputation             5

# Comparando o Futebol da India com o da Russia

In [27]:
x = data[(data['Nationality'] == 'Russia') | (data['Nationality'] == 'India')]
x[['Nationality','Overall','Potential']].groupby(['Nationality']).agg('mean').style.background_gradient(cmap = 'copper')

# Jogador mais popular com menos de 20 anos

In [28]:
x = data[data['Age'] < 20]

def extract_value_from(column):
    out = column.replace('€', '')
    if 'M' in out:
        out = float(out.replace('M', ''))*1000000
    elif 'K' in column:
        out = float(out.replace('K', ''))*1000
    return float(out)

x['Value'] = x['Value'].apply(extract_value_from)

x[['Name','Age','Value']].sort_values(by = 'Value', ascending = False).head(10).style.background_gradient(cmap = 'copper')

<ipython-input-28-b2160681bc4e>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Value'] = x['Value'].apply(extract_value_from)